// flow-typed signature: a2a4fc7125f4a28a85cbc0b197e2e3ee
// flow-typed version: <<STUB>>/@vitest/coverage-c8_v^0.29.2/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vitest/coverage-c8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vitest/coverage-c8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vitest/coverage-c8/dist' {
  declare module.exports: any;
}

declare module '@vitest/coverage-c8/dist/provider' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vitest/coverage-c8/dist/index' {
  declare module.exports: $Exports<'@vitest/coverage-c8/dist'>;
}
declare module '@vitest/coverage-c8/dist/index.js' {
  declare module.exports: $Exports<'@vitest/coverage-c8/dist'>;
}
declare module '@vitest/coverage-c8/dist/provider.js' {
  declare module.exports: $Exports<'@vitest/coverage-c8/dist/provider'>;
}
