// flow-typed signature: 6fd04c7e23e221af33eaa84fe8f28617
// flow-typed version: <<STUB>>/@vitest/ui_v^0.29.2/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vitest/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vitest/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vitest/ui/dist/client/assets/index-84967894' {
  declare module.exports: any;
}

declare module '@vitest/ui/dist' {
  declare module.exports: any;
}

declare module '@vitest/ui/dist/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vitest/ui/dist/client/assets/index-84967894.js' {
  declare module.exports: $Exports<'@vitest/ui/dist/client/assets/index-84967894'>;
}
declare module '@vitest/ui/dist/index' {
  declare module.exports: $Exports<'@vitest/ui/dist'>;
}
declare module '@vitest/ui/dist/index.js' {
  declare module.exports: $Exports<'@vitest/ui/dist'>;
}
declare module '@vitest/ui/dist/reporter.js' {
  declare module.exports: $Exports<'@vitest/ui/dist/reporter'>;
}
