// flow-typed signature: 007f5502c78e3f37f71997db4073d21d
// flow-typed version: <<STUB>>/vitest_v^0.29.2/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vitest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vitest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vitest/dist/browser' {
  declare module.exports: any;
}

declare module 'vitest/dist/child' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-api-setup.3aabe9ac' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-constants.bc18a549' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-env-node.affdd278' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-install-pkg.6aa7cf6d' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-integrations-coverage.d93ee824' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-integrations-globals.49802775' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-integrations-run-once.ea614f17' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-integrations-utils.23c19408' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-node-git.ed5bded8' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-node-pkg.30d8b37e' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-paths.e36446b4' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-runtime-inspector.b1427a10' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-runtime-mocker.3283818a' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-runtime-rpc.d6aa57f8' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-runtime-setup.5d504677' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-snapshot-env.a347d647' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-utils-base.b5ddfcc9' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-utils-env.6b856dbf' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-utils-global.fd174983' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-utils-import.e488ace3' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunk-utils-tasks.8781fd71' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli-wrapper' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli' {
  declare module.exports: any;
}

declare module 'vitest/dist/config' {
  declare module.exports: any;
}

declare module 'vitest/dist/coverage' {
  declare module.exports: any;
}

declare module 'vitest/dist/entry' {
  declare module.exports: any;
}

declare module 'vitest/dist/environments' {
  declare module.exports: any;
}

declare module 'vitest/dist' {
  declare module.exports: any;
}

declare module 'vitest/dist/loader' {
  declare module.exports: any;
}

declare module 'vitest/dist/node' {
  declare module.exports: any;
}

declare module 'vitest/dist/runners' {
  declare module.exports: any;
}

declare module 'vitest/dist/spy' {
  declare module.exports: any;
}

declare module 'vitest/dist/suite' {
  declare module.exports: any;
}

declare module 'vitest/dist/utils' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-_commonjsHelpers.addc3445' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.2cbcdd1e' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.534e612c' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.783e7f3e' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-index.bdee400f' {
  declare module.exports: any;
}

declare module 'vitest/dist/vendor-magic-string.es.b3bc5745' {
  declare module.exports: any;
}

declare module 'vitest/dist/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vitest/dist/browser.js' {
  declare module.exports: $Exports<'vitest/dist/browser'>;
}
declare module 'vitest/dist/child.js' {
  declare module.exports: $Exports<'vitest/dist/child'>;
}
declare module 'vitest/dist/chunk-api-setup.3aabe9ac.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-api-setup.3aabe9ac'>;
}
declare module 'vitest/dist/chunk-constants.bc18a549.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-constants.bc18a549'>;
}
declare module 'vitest/dist/chunk-env-node.affdd278.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-env-node.affdd278'>;
}
declare module 'vitest/dist/chunk-install-pkg.6aa7cf6d.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-install-pkg.6aa7cf6d'>;
}
declare module 'vitest/dist/chunk-integrations-coverage.d93ee824.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-integrations-coverage.d93ee824'>;
}
declare module 'vitest/dist/chunk-integrations-globals.49802775.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-integrations-globals.49802775'>;
}
declare module 'vitest/dist/chunk-integrations-run-once.ea614f17.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-integrations-run-once.ea614f17'>;
}
declare module 'vitest/dist/chunk-integrations-utils.23c19408.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-integrations-utils.23c19408'>;
}
declare module 'vitest/dist/chunk-node-git.ed5bded8.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-node-git.ed5bded8'>;
}
declare module 'vitest/dist/chunk-node-pkg.30d8b37e.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-node-pkg.30d8b37e'>;
}
declare module 'vitest/dist/chunk-paths.e36446b4.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-paths.e36446b4'>;
}
declare module 'vitest/dist/chunk-runtime-inspector.b1427a10.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-runtime-inspector.b1427a10'>;
}
declare module 'vitest/dist/chunk-runtime-mocker.3283818a.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-runtime-mocker.3283818a'>;
}
declare module 'vitest/dist/chunk-runtime-rpc.d6aa57f8.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-runtime-rpc.d6aa57f8'>;
}
declare module 'vitest/dist/chunk-runtime-setup.5d504677.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-runtime-setup.5d504677'>;
}
declare module 'vitest/dist/chunk-snapshot-env.a347d647.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-snapshot-env.a347d647'>;
}
declare module 'vitest/dist/chunk-utils-base.b5ddfcc9.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-utils-base.b5ddfcc9'>;
}
declare module 'vitest/dist/chunk-utils-env.6b856dbf.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-utils-env.6b856dbf'>;
}
declare module 'vitest/dist/chunk-utils-global.fd174983.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-utils-global.fd174983'>;
}
declare module 'vitest/dist/chunk-utils-import.e488ace3.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-utils-import.e488ace3'>;
}
declare module 'vitest/dist/chunk-utils-tasks.8781fd71.js' {
  declare module.exports: $Exports<'vitest/dist/chunk-utils-tasks.8781fd71'>;
}
declare module 'vitest/dist/cli-wrapper.js' {
  declare module.exports: $Exports<'vitest/dist/cli-wrapper'>;
}
declare module 'vitest/dist/cli.js' {
  declare module.exports: $Exports<'vitest/dist/cli'>;
}
declare module 'vitest/dist/config.js' {
  declare module.exports: $Exports<'vitest/dist/config'>;
}
declare module 'vitest/dist/coverage.js' {
  declare module.exports: $Exports<'vitest/dist/coverage'>;
}
declare module 'vitest/dist/entry.js' {
  declare module.exports: $Exports<'vitest/dist/entry'>;
}
declare module 'vitest/dist/environments.js' {
  declare module.exports: $Exports<'vitest/dist/environments'>;
}
declare module 'vitest/dist/index' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/index.js' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/loader.js' {
  declare module.exports: $Exports<'vitest/dist/loader'>;
}
declare module 'vitest/dist/node.js' {
  declare module.exports: $Exports<'vitest/dist/node'>;
}
declare module 'vitest/dist/runners.js' {
  declare module.exports: $Exports<'vitest/dist/runners'>;
}
declare module 'vitest/dist/spy.js' {
  declare module.exports: $Exports<'vitest/dist/spy'>;
}
declare module 'vitest/dist/suite.js' {
  declare module.exports: $Exports<'vitest/dist/suite'>;
}
declare module 'vitest/dist/utils.js' {
  declare module.exports: $Exports<'vitest/dist/utils'>;
}
declare module 'vitest/dist/vendor-_commonjsHelpers.addc3445.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-_commonjsHelpers.addc3445'>;
}
declare module 'vitest/dist/vendor-index.2cbcdd1e.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.2cbcdd1e'>;
}
declare module 'vitest/dist/vendor-index.534e612c.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.534e612c'>;
}
declare module 'vitest/dist/vendor-index.783e7f3e.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.783e7f3e'>;
}
declare module 'vitest/dist/vendor-index.bdee400f.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-index.bdee400f'>;
}
declare module 'vitest/dist/vendor-magic-string.es.b3bc5745.js' {
  declare module.exports: $Exports<'vitest/dist/vendor-magic-string.es.b3bc5745'>;
}
declare module 'vitest/dist/worker.js' {
  declare module.exports: $Exports<'vitest/dist/worker'>;
}
